**Hand Written Digit Prediction -Classification Analysis**

 The digits dataset consists of 8x8 pixel images of digits. The images attribute of the dataset stores 8x8 arrays of grayscale values for each image. We will use these arrays to visualize the first 4 images. The target attribute of the dataset stores the digit each image represents



 **Import Library**

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

Import Data

In [4]:
from sklearn.datasets import load_digits

In [5]:
df = load_digits()

In [10]:
_, axes = plt.subplots(nrows=1, ncols=4, figsize=(10,3))
for ax,image,label in zip(axes,df.images,df.target):
    ax.set_axis_off()
    ax.imshow(image, cmap=plt.cm.gray_r,interpolation="nearest")
    ax.set_title("Training: %i" % label)

Data Preprocessing
flatten image

In [11]:
df.images.shape

(1797, 8, 8)

In [12]:
df.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [13]:
df.images[0].shape

(8, 8)

In [14]:
len(df.images)

1797

In [16]:
n_samples = len(df.images)
data = df.images.reshape((n_samples,-1))

In [17]:
data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [18]:
data[0].shape

(64,)

In [19]:
data.shape

(1797, 64)

Scaling Image Data

In [22]:
data.min()

0.0

In [21]:
data.max()

16.0

In [23]:
data = data/16

In [24]:
data.min()

0.0

In [25]:
data.max()

1.0

In [26]:
data[0]

array([0.    , 0.    , 0.3125, 0.8125, 0.5625, 0.0625, 0.    , 0.    ,
       0.    , 0.    , 0.8125, 0.9375, 0.625 , 0.9375, 0.3125, 0.    ,
       0.    , 0.1875, 0.9375, 0.125 , 0.    , 0.6875, 0.5   , 0.    ,
       0.    , 0.25  , 0.75  , 0.    , 0.    , 0.5   , 0.5   , 0.    ,
       0.    , 0.3125, 0.5   , 0.    , 0.    , 0.5625, 0.5   , 0.    ,
       0.    , 0.25  , 0.6875, 0.    , 0.0625, 0.75  , 0.4375, 0.    ,
       0.    , 0.125 , 0.875 , 0.3125, 0.625 , 0.75  , 0.    , 0.    ,
       0.    , 0.    , 0.375 , 0.8125, 0.625 , 0.    , 0.    , 0.    ])

**Train test split Data**

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train,X_test,y_train,y_test =train_test_split(data,df.target,test_size=0.3)

In [29]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((1257, 64), (540, 64), (1257,), (540,))

**Random Forest Model**

In [62]:
from sklearn.ensemble import RandomForestClassifier

In [63]:
rf=RandomForestClassifier()

In [64]:
rf.fit(X_train,y_train)

RandomForestClassifier()

Predict

In [66]:
y_pred =rf.predict(X_test)

In [67]:
y_pred

array([2, 3, 4, 2, 7, 8, 6, 5, 0, 1, 0, 8, 9, 5, 9, 6, 3, 3, 7, 7, 6, 1,
       2, 0, 4, 4, 4, 2, 6, 2, 2, 7, 2, 2, 7, 3, 2, 3, 1, 7, 2, 7, 3, 0,
       7, 0, 8, 5, 8, 6, 6, 9, 9, 5, 7, 3, 1, 5, 0, 8, 8, 1, 0, 1, 7, 7,
       5, 0, 2, 9, 7, 0, 0, 3, 5, 4, 6, 1, 3, 8, 9, 1, 5, 0, 5, 7, 1, 0,
       5, 7, 6, 2, 3, 9, 1, 5, 1, 9, 4, 9, 0, 9, 8, 5, 4, 4, 8, 9, 6, 6,
       7, 7, 1, 0, 5, 9, 7, 5, 3, 8, 7, 4, 4, 3, 8, 8, 8, 2, 4, 1, 0, 9,
       0, 7, 1, 9, 5, 2, 5, 8, 0, 0, 7, 4, 5, 1, 2, 5, 7, 5, 4, 3, 0, 1,
       7, 9, 2, 9, 4, 3, 8, 1, 6, 4, 6, 6, 0, 7, 7, 6, 3, 2, 3, 8, 2, 9,
       8, 7, 2, 8, 9, 4, 6, 3, 0, 8, 6, 4, 5, 5, 4, 4, 9, 2, 2, 1, 1, 3,
       9, 9, 3, 9, 9, 3, 6, 5, 1, 2, 8, 3, 2, 4, 8, 4, 9, 2, 7, 7, 5, 4,
       2, 9, 4, 6, 8, 8, 3, 0, 2, 3, 1, 7, 6, 1, 0, 9, 8, 6, 1, 7, 4, 2,
       2, 9, 8, 8, 2, 8, 9, 5, 6, 6, 4, 7, 2, 4, 5, 4, 0, 1, 0, 2, 7, 7,
       8, 1, 8, 6, 5, 0, 8, 2, 5, 6, 6, 7, 7, 5, 1, 7, 8, 0, 8, 3, 2, 7,
       1, 3, 2, 9, 0, 1, 9, 6, 6, 1, 5, 4, 9, 2, 4,

Model Accuracy


In [68]:
from sklearn.metrics import confusion_matrix, classification_report

In [69]:
confusion_matrix(y_test,y_pred)

array([[55,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0, 54,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 58,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 53,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0, 57,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0, 50,  1,  0,  1,  0],
       [ 1,  0,  0,  0,  1,  0, 50,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 47,  0,  0],
       [ 0,  2,  1,  0,  0,  0,  0,  0, 46,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  4,  1, 52]])

In [70]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        56
           1       0.96      1.00      0.98        54
           2       0.98      1.00      0.99        58
           3       0.98      0.96      0.97        55
           4       0.97      0.97      0.97        59
           5       1.00      0.96      0.98        52
           6       0.98      0.96      0.97        52
           7       0.85      1.00      0.92        47
           8       0.96      0.94      0.95        49
           9       1.00      0.90      0.95        58

    accuracy                           0.97       540
   macro avg       0.97      0.97      0.97       540
weighted avg       0.97      0.97      0.97       540

